modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ironcomputing"
version = "${version}"
displayName = "IronComputing"
authors = "DecDuck"
description = '''
Adds computers and related equipment that runs WASM binaries that can interact with the world.
'''
#logoFile = ""

[[dependencies.ironcomputing]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ironcomputing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ironcomputing]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
